name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Libs folder
      run: mkdir ./libs-
    - name: Download Dependencies
      run: wget https://dl.reforged.gg/2Y4PQlr -O ./libs-/Pixelmon-1.12.2-7.1.1-server.jar
    - name: Build with Gradle
      run: ./gradlew build --scan -s
